### ISSUE TITLE
Adding buttons 

### ISSUE THREAD

**Issue by cmsethi** [onyx-and-iris/voicemeeter-compact#17]
Hi, the app/GUI is working fine. As you suggested, I have disabled the menubar, but if I want to shutdown or reload the app, I have two options:
1) Create a system tray icon menu.
2) Add a few buttons to the interface.
I would prefer to have some buttons on the interface, but I am not able to add those.
Any help is appreciated. Thanks

**Comment by onyx-and-iris** [comment]
Hi.

I won't start adding new buttons to the GUI but I can offer you some pointers. If, for example, you don't need the `SUBMIX` button in the navigation frame, you could replace it with a `CLOSE` button using the following steps:

in `builders.py`:
- modify `create_submix_button()` in NavigationFrameBuilder like so:
```python
    def create_submix_button(self):
        self.navframe.submix_button = ttk.Checkbutton(
            self.navframe,
            text="CLOSE",
            command=self.navframe.show_submix,
            style=f"{'Toggle.TButton' if _configuration.themes_enabled else f'Submix.TButton'}",
            variable=self.navframe.submix,
        )
        self.navframe.submix_button.grid(column=0, row=0)
        # if self.navframe.parent.kind.name != "potato":
        # self.navframe.submix_button["state"] = "disabled"
```

in `navigation.py`:

- replace the body of the `show_submix()` callback function like so:
```python
    def show_submix(self):
        self.parent.destroy()
```

Similar steps could be followed to modify/add more buttons to the Navigation frame. 

First change it's step method in the Builder class, then modify the button callback function to do whatever you require.

As for reloading the app, I suppose you mean redrawing the frames? In which case you'd need to destroy the top level frames then rerender them according to a kind.

Something like this should work:
```python
        self.parent._destroy_top_level_frames()
        self.parent.build_app(self.parent._vmr.kind)
```

I hope that is helpful.

**Comment by cmsethi** [comment]
Thanks for the help

> Hi.
> 
> I won't start adding new buttons to the GUI but I can offer you some pointers. If, for example, you don't need the `SUBMIX` button in the navigation frame, you could replace it with a `CLOSE` button using the following steps:
> 
> in `builders.py`:
> 
>     * modify `create_submix_button()` in NavigationFrameBuilder like so:
> 
> 
> ```python
>     def create_submix_button(self):
>         self.navframe.submix_button = ttk.Checkbutton(
>             self.navframe,
>             text="CLOSE",
>             command=self.navframe.show_submix,
>             style=f"{'Toggle.TButton' if _configuration.themes_enabled else f'Submix.TButton'}",
>             variable=self.navframe.submix,
>         )
>         self.navframe.submix_button.grid(column=0, row=0)
>         # if self.navframe.parent.kind.name != "potato":
>         # self.navframe.submix_button["state"] = "disabled"
> ```
> 
> in `navigation.py`:
> 
>     * replace the body of the `show_submix()` callback function like so:
> 
> 
> ```python
>     def show_submix(self):
>         self.parent.destroy()
> ```
> 
> Similar steps could be followed to modify/add more buttons to the Navigation frame.
> 
> First change it's step method in the Builder class, then modify the button callback function to do whatever you require.
> 
> As for reloading the app, I suppose you mean redrawing the frames? In which case you'd need to destroy the top level frames then rerender them according to a kind.
> 
> Something like this should work:
> 
> ```python
>         self.parent._destroy_top_level_frames()
>         self.parent.build_app(self.parent._vmr.kind)
> ```
> 
> I hope that is helpful.
